### ISSUE TITLE
Breaks on newer kotlinx-coroutines

### ISSUE THREAD

**Issue by Fuyukai** [cy6erGn0m/kotlinx-sockets#1]
```
Exception in thread "main" java.lang.NoSuchMethodError: kotlinx.coroutines.experimental.CancellableContinuationImpl.<init>(Lkotlin/coroutines/experimental/Continuation;Z)V
	at kotlinx.sockets.selector.SelectorManagerSupport$select$1.doResume(SelectorManagerSupport.kt:99)
	at kotlinx.sockets.selector.SelectorManagerSupport.select(SelectorManagerSupport.kt)
	at kotlinx.sockets.selector.OnDemandSelectorManager$select$1.doResume(OnDemandSelectorManager.kt:31)
	at kotlinx.sockets.selector.OnDemandSelectorManager.select(OnDemandSelectorManager.kt)
	at kotlinx.sockets.impl.ServerSocketImpl$accept$1.doResume(ServerSocketImpl.kt:22)
	at kotlinx.sockets.impl.ServerSocketImpl.accept(ServerSocketImpl.kt)
	at tf.veriny.hmq.HMQServer$serve$1.doResume(server.kt:39)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:235)
	at kotlinx.coroutines.experimental.EventLoopImpl$QueuedRunnableTask.invoke(EventLoop.kt:156)
	at kotlinx.coroutines.experimental.EventLoopImpl$QueuedRunnableTask.invoke(EventLoop.kt:153)
	at kotlinx.coroutines.experimental.EventLoopImpl.processNextEvent(EventLoop.kt:111)
	at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:205)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Builders.kt:150)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking$default(Builders.kt:142)
	at tf.veriny.hmq.HMQServer.serve(server.kt:30)
	at tf.veriny.hmq.MainKt.main(main.kt:17)```

**Comment by sergeymild** [comment]
The same problem

**Comment by RiadGahlouz** [comment]
![image](https://user-images.githubusercontent.com/1711217/51878938-82730a80-233f-11e9-86d7-356fe40eb3b9.png)

I also have this problem

**Comment by fgutmann** [comment]
I think this library has been moved to ktor.
https://ktor.io/servers/raw-sockets.html

@cy6erGn0m Can you confirm this? If true, we should mention this in the Readme because this is is one of the top hits for "kotlin socket" on google.
